# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'enmaxtraining_sc'
    subscriptionId: '4ecbfc9e-1005-4884-8e56-7fea16f1a054'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'enmaxtraning'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'database_deploy.json'
    csmParametersFile: 'database_deploy.parameters.json'
    deploymentMode: 'Incremental'
